e2e_de_project:
  outputs:
    dev:
      dbname: e2e_de_project
      host: "{{ env_var('DB_HOST_PROD') }}"
      pass: "{{ env_var('DB_PASS_PROD') }}"
      port: "{{ env_var('DB_PORT_PROD') | int }}"
      schema: "{{ env_var('DB_SCHEMA_PROD')}}"
      threads: "{{ env_var('DB_THREADS_PROD') | int }}"
      type: "{{ env_var('DB_TYPE_PROD') }}"
      user: "{{ env_var('DB_USER_PROD') }}"
  target: dev
